# Generated by Django 5.0.4 on 2024-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Whiskey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
